// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ebagalunwuvhisjfcfeo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImViYWdhbHVud3V2aGlzamZjZmVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzNzkwNzIsImV4cCI6MjA2OTk1NTA3Mn0.83fnwFdy_rgvjcyDK_B5eDRjhA_MvC5SqEjHPr5fiLo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});